name: city_events_explorer
description: A Flutter application for browsing, searching, and saving favourite city events.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_map: ^7.0.2
  freezed_annotation: ^2.4.4
  get_it: ^8.0.2
  go_router: ^14.6.2
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  shared_preferences: ^2.3.3

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
