name: city_events_explorer
description: A Flutter application for browsing, searching, and saving favourite city events.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ^3.5.0

dependencies:
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_map: ^8.2.2
  freezed_annotation: ^3.1.0
  get_it: ^9.2.0
  go_router: ^17.1.0
  injectable: ^2.5.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  latlong2: ^0.9.1
  shared_preferences: ^2.3.3

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed: ^3.2.5
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/
